version: 3
tasks:
  build:
    desc: "Build"
    cmds:
      - cargo build

  install:
    desc: "Install"

    deps:
      - build
    cmds:
      - install target/debug/wlout ~/.local/bin

  video:
    cmds:
      - ffmpeg -i wlout.mp4 -vf "fps=12,scale=800:-1:flags=lanczos,palettegen" palette.png
      - ffmpeg -i wlout.mp4 -i palette.png -lavfi "fps=12,scale=800:-1:flags=lanczos[x]; [x][1:v] paletteuse=dither=sierra2_4a" -loop 0 video.gif

  publish_minor:
    desc: "Increment a minor version and publish to AUR"
    cmds:
      - task: publish
        vars:
          INCREMENT: minor

  publish_patch:
    desc: "Increment a patch version and publish to AUR"
    cmds:
      - task: publish
        vars:
          INCREMENT: patch

  generate_doc:
    cmds:
      - |
        cargo run --bin generate_readme --features="markdown" > README.md
      - |
        cargo run --bin generate_full_ref --features="markdown" > REFERENCE.md

  publish:
    internal: true
    preconditions:
      - sh: git diff --quiet
        msg: "Git Worktree not Clean"

    prompt:
      - echo "Publishing {{.INCREMENT}}"

    deps:
      - task: generate_doc

    cmds:
      - cargo install cargo-get
      - cargo install cargo-edit
      - cargo set-version --bump {{.INCREMENT}}
      - cargo build --profile=release
      - |
        export NEW_VERSION=$(cargo get package.version)
        git commit -am "version: $NEW_VERSION"
        git tag $NEW_VERSION
        git push origin $NEW_VERSION
        sed -Ei "s/pkgver=(.*)/pkgver=$NEW_VERSION/g" pkgbase/PKGBUILD
        sed -Ei "s/tag=[^\"]*/tag=$NEW_VERSION/g" pkgbase/PKGBUILD
        cd pkgbase
        makepkg --printsrcinfo > .SRCINFO
        git commit -am "version: $NEW_VERSION"
        git push origin master
